- name: put /root/k8s-cassandra-config.yaml
  template: src=k8s-cassandra-config.yaml dest=/root/k8s-cassandra-config.yaml

- name: create /data/pvs
  file: dest=/data/pvs state=directory owner=root mode=0600

- name: put a cassandra-pv1.yaml file
  template: src=pv1.yaml dest=/root/cassandra-pv1.yaml

- name: check if a PV exist
  shell: kubectl get persistentvolumes --namespace={{ cassandra_cluster_namespace }} | grep cassandra-data-1
  register: result
  ignore_errors: true

- name: deploy a persistent volume
  shell: kubectl create --namespace={{ cassandra_cluster_namespace }} -f /root/cassandra-pv1.yaml
  when: result|failed

- name: put a cassandra-pv2.yaml file
  template: src=pv2.yaml dest=/root/cassandra-pv2.yaml

- name: check if a PV exist
  shell: kubectl get persistentvolumes --namespace={{ cassandra_cluster_namespace }} | grep cassandra-data-2
  register: result
  ignore_errors: true

- name: deploy a persistent volume
  shell: kubectl create --namespace={{ cassandra_cluster_namespace }} -f /root/cassandra-pv2.yaml
  when: result|failed

- name: put a cassandra-pv3.yaml file
  template: src=pv3.yaml dest=/root/cassandra-pv3.yaml

- name: check if a PV exist
  shell: kubectl get persistentvolumes --namespace={{ cassandra_cluster_namespace }} | grep cassandra-data-3
  register: result
  ignore_errors: true

- name: deploy a persistent volume
  shell: kubectl create --namespace={{ cassandra_cluster_namespace }} -f /root/cassandra-pv3.yaml
  when: result|failed

- name: check if a Helm release for cassandra-cluster is present
  shell: helm list --namespace={{ cassandra_cluster_namespace }} | grep cassandra-cluster-release
  register: result
  ignore_errors: true

- name: enable the incubator repo
  shell: helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/

- name: install a Cassandra cluster using a Helm chart
  shell: helm install -f /root/k8s-cassandra-config.yaml incubator/cassandra --namespace {{ cassandra_cluster_namespace }} --name cassandra-cluster-release
  when: result|failed
