kind: PersistentVolume
apiVersion: v1
metadata:
  name: cassandra-data-1
  labels:
    type: local
spec:
  storageClassName: cassandra
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pvs/cassandra-cluster-pv-1"
